# Leviton Cloud Services API model Action.
# Auto-generated by api_scraper.py.
#
# Copyright 2017 Tim Lyakhovetskiy <tlyakhov@gmail.com>
#
# This code is released under the terms of the MIT license. See the LICENSE
# file for more details.
from decora_wifi.base_model import BaseModel


class Action(BaseModel):
    def __init__(self, session, model_id=None):
        super(Action, self).__init__(session, model_id)

    def count(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_action_block_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_installation_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_action_block_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_installation_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_action_block_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_installation_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def delete_action_block_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_installation_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_action_block_actions(self, action, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions/{1}".format(self._id, action)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_installation_actions(self, action, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions/{1}".format(self._id, action)
        return self._session.call_api(api, attribs, 'delete')

    def exists(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/{0}/exists".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_action_block_actions(self, action, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions/{1}".format(self._id, action)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_installation_actions(self, action, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions/{1}".format(self._id, action)
        return self._session.call_api(api, attribs, 'get')

    def find_one(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/findOne".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/{0}".format(self._id)
        data = self._session.call_api(api, attribs, 'get')

        self.set_model_data(data)
        return self

        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_action_block(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/:id/actionBlock"
        return session.call_api(api, attribs, 'get')

    def get_action_block_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get_installation_actions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def replace_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/{0}/replace".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def replace_or_create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/replaceOrCreate".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    @classmethod
    def update_attributes(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/:id"
        return session.call_api(api, attribs, 'put')

    def update_by_id_action_block_actions(self, action, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ActionBlocks/{0}/actions/{1}".format(self._id, action)
        return self._session.call_api(api, attribs, 'put')

    def update_by_id_installation_actions(self, action, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/actions/{1}".format(self._id, action)
        return self._session.call_api(api, attribs, 'put')

    def upsert(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions".format(self._id)
        return self._session.call_api(api, attribs, 'put')

    def upsert_with_where(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Actions/upsertWithWhere".format(self._id)
        return self._session.call_api(api, attribs, 'post')

