# Leviton Cloud Services API model ResidentialArea.
# Auto-generated by api_scraper.py.
#
# Copyright 2017 Tim Lyakhovetskiy <tlyakhov@gmail.com>
#
# This code is released under the terms of the MIT license. See the LICENSE
# file for more details.
from decora_wifi.base_model import BaseModel


class ResidentialArea(BaseModel):
    def __init__(self, session, model_id=None):
        super(ResidentialArea, self).__init__(session, model_id)

    def count(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_residence_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_residence_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_residence_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def delete_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_residence_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_residence_residential_areas(self, residential_area, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas/{1}".format(self._id, residential_area)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_residential_room_residential_areas(self, residential_area, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/{1}".format(self._id, residential_area)
        return self._session.call_api(api, attribs, 'delete')

    def exists(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/{0}/exists".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def exists_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/rel/{1}".format(self._id, None)
        return self._session.call_api(api, attribs, 'head')

    def find(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_residence_residential_areas(self, residential_area, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas/{1}".format(self._id, residential_area)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_residential_room_residential_areas(self, residential_area, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/{1}".format(self._id, residential_area)
        return self._session.call_api(api, attribs, 'get')

    def find_one(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/findOne".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/{0}".format(self._id)
        data = self._session.call_api(api, attribs, 'get')

        self.set_model_data(data)
        return self

        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_residence(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/:id/residence"
        return session.call_api(api, attribs, 'get')

    def get_residence_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def link_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/rel/{1}".format(self._id, None)
        return self._session.call_api(api, attribs, 'put')

    def replace_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/{0}/replace".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def replace_or_create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/replaceOrCreate".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def unlink_residential_room_residential_areas(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/rel/{1}".format(self._id, None)
        return self._session.call_api(api, attribs, 'delete')

    @classmethod
    def update_attributes(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/:id"
        return session.call_api(api, attribs, 'put')

    def update_by_id_residence_residential_areas(self, residential_area, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Residences/{0}/residentialAreas/{1}".format(self._id, residential_area)
        return self._session.call_api(api, attribs, 'put')

    def update_by_id_residential_room_residential_areas(self, residential_area, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialRooms/{0}/residentialAreas/{1}".format(self._id, residential_area)
        return self._session.call_api(api, attribs, 'put')

    def upsert(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas".format(self._id)
        return self._session.call_api(api, attribs, 'put')

    def upsert_with_where(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ResidentialAreas/upsertWithWhere".format(self._id)
        return self._session.call_api(api, attribs, 'post')

