# Leviton Cloud Services API model SensorSnapshot.
# Auto-generated by api_scraper.py.
#
# Copyright 2017 Tim Lyakhovetskiy <tlyakhov@gmail.com>
#
# This code is released under the terms of the MIT license. See the LICENSE
# file for more details.
from decora_wifi.base_model import BaseModel


class SensorSnapshot(BaseModel):
    def __init__(self, session, model_id=None):
        super(SensorSnapshot, self).__init__(session, model_id)

    def count(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_installation_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_sensor_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_change_stream(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/change-stream".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_installation_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_installation_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_sensor_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_sensor_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def delete_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_installation_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_sensor_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_installation_sensor_snapshots(self, sensor_snapshot, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots/{1}".format(self._id, sensor_snapshot)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_sensor_sensor_snapshots(self, sensor_snapshot, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots/{1}".format(self._id, sensor_snapshot)
        return self._session.call_api(api, attribs, 'delete')

    def exists(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/{0}/exists".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_installation_sensor_snapshots(self, sensor_snapshot, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots/{1}".format(self._id, sensor_snapshot)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_sensor_sensor_snapshots(self, sensor_snapshot, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots/{1}".format(self._id, sensor_snapshot)
        return self._session.call_api(api, attribs, 'get')

    def find_one(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/findOne".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/{0}".format(self._id)
        data = self._session.call_api(api, attribs, 'get')

        self.set_model_data(data)
        return self

        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_area(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/:id/area"
        return session.call_api(api, attribs, 'get')

    @classmethod
    def get_installation(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/:id/installation"
        return session.call_api(api, attribs, 'get')

    def get_installation_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_sensor(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/:id/sensor"
        return session.call_api(api, attribs, 'get')

    def get_sensor_sensor_snapshots(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def replace_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/{0}/replace".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def replace_or_create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/replaceOrCreate".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def update_all(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/update".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    @classmethod
    def update_attributes(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/:id"
        return session.call_api(api, attribs, 'put')

    def update_by_id_installation_sensor_snapshots(self, sensor_snapshot, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/sensorSnapshots/{1}".format(self._id, sensor_snapshot)
        return self._session.call_api(api, attribs, 'put')

    def update_by_id_sensor_sensor_snapshots(self, sensor_snapshot, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Sensors/{0}/sensorSnapshots/{1}".format(self._id, sensor_snapshot)
        return self._session.call_api(api, attribs, 'put')

    def upsert(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots".format(self._id)
        return self._session.call_api(api, attribs, 'put')

    def upsert_with_where(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/SensorSnapshots/upsertWithWhere".format(self._id)
        return self._session.call_api(api, attribs, 'post')

