# Leviton Cloud Services API model ThermostatDefinition.
# Auto-generated by api_scraper.py.
#
# Copyright 2017 Tim Lyakhovetskiy <tlyakhov@gmail.com>
#
# This code is released under the terms of the MIT license. See the LICENSE
# file for more details.
from decora_wifi.base_model import BaseModel


class ThermostatDefinition(BaseModel):
    def __init__(self, session, model_id=None):
        super(ThermostatDefinition, self).__init__(session, model_id)

    def count(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def count_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList/count"
        return session.call_api(api, attribs, 'get')

    def count_whitelist_thermostat_definitions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    @classmethod
    def create_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList"
        return session.call_api(api, attribs, 'post')

    def create_many(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_whitelist_thermostat_definitions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_whitelist_thermostat_definitions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def delete_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    @classmethod
    def delete_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList"
        return session.call_api(api, attribs, 'delete')

    def delete_whitelist_thermostat_definitions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    @classmethod
    def destroy_by_id_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList/{0}"
        return session.call_api(api, attribs, 'delete')

    def destroy_by_id_whitelist_thermostat_definitions(self, thermostat_definition, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions/{1}".format(self._id, thermostat_definition)
        return self._session.call_api(api, attribs, 'delete')

    def exists(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/{0}/exists".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def find_by_id_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList/{0}"
        return session.call_api(api, attribs, 'get')

    def find_by_id_whitelist_thermostat_definitions(self, thermostat_definition, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions/{1}".format(self._id, thermostat_definition)
        return self._session.call_api(api, attribs, 'get')

    def find_one(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/findOne".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/{0}".format(self._id)
        data = self._session.call_api(api, attribs, 'get')

        self.set_model_data(data)
        return self

        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList"
        return session.call_api(api, attribs, 'get')

    def get_thermostat_device_definition(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Thermostats/{0}/deviceDefinition".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_whitelist(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/whitelist"
        return session.call_api(api, attribs, 'get')

    def get_whitelist_thermostat_definitions(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def replace_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/{0}/replace".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def replace_or_create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/replaceOrCreate".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    @classmethod
    def update_attributes(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id"
        return session.call_api(api, attribs, 'put')

    @classmethod
    def update_by_id_firmware_list(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/:id/firmwareList/{0}"
        return session.call_api(api, attribs, 'put')

    def update_by_id_whitelist_thermostat_definitions(self, thermostat_definition, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Whitelist/{0}/thermostatDefinitions/{1}".format(self._id, thermostat_definition)
        return self._session.call_api(api, attribs, 'put')

    def upsert(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions".format(self._id)
        return self._session.call_api(api, attribs, 'put')

    def upsert_with_where(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/ThermostatDefinitions/upsertWithWhere".format(self._id)
        return self._session.call_api(api, attribs, 'post')

