# Leviton Cloud Services API model Touchscreen.
# Auto-generated by api_scraper.py.
#
# Copyright 2017 Tim Lyakhovetskiy <tlyakhov@gmail.com>
#
# This code is released under the terms of the MIT license. See the LICENSE
# file for more details.
from decora_wifi.base_model import BaseModel


class Touchscreen(BaseModel):
    def __init__(self, session, model_id=None):
        super(Touchscreen, self).__init__(session, model_id)

    def count(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def count_installation_touchscreens(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens/count".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_installation_touchscreens(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def create_many_installation_touchscreens(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def delete_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def delete_installation_touchscreens(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'delete')

    def destroy_by_id_installation_touchscreens(self, touchscreen, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens/{1}".format(self._id, touchscreen)
        return self._session.call_api(api, attribs, 'delete')

    def exists(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/{0}/exists".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/{0}".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def find_by_id_installation_touchscreens(self, touchscreen, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens/{1}".format(self._id, touchscreen)
        return self._session.call_api(api, attribs, 'get')

    def find_one(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/findOne".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def get(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/{0}".format(self._id)
        data = self._session.call_api(api, attribs, 'get')

        self.set_model_data(data)
        return self

        return self._session.call_api(api, attribs, 'get')

    @classmethod
    def get_area(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/:id/area"
        return session.call_api(api, attribs, 'get')

    @classmethod
    def get_device_definition(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/:id/deviceDefinition"
        return session.call_api(api, attribs, 'get')

    @classmethod
    def get_installation(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/:id/installation"
        return session.call_api(api, attribs, 'get')

    def get_installation_touchscreens(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'get')

    def replace_by_id(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/{0}/replace".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    def replace_or_create(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/replaceOrCreate".format(self._id)
        return self._session.call_api(api, attribs, 'post')

    @classmethod
    def update_attributes(cls, session, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/:id"
        return session.call_api(api, attribs, 'put')

    def update_by_id_installation_touchscreens(self, touchscreen, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Installations/{0}/touchscreens/{1}".format(self._id, touchscreen)
        return self._session.call_api(api, attribs, 'put')

    def upsert(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens".format(self._id)
        return self._session.call_api(api, attribs, 'put')

    def upsert_with_where(self, attribs=None):
        if attribs is None:
            attribs = {}
        api = "/Touchscreens/upsertWithWhere".format(self._id)
        return self._session.call_api(api, attribs, 'post')

